# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Steam520
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Update hosts
        run: npm run make

      - name: Commit changes
        id: commit
        run: |
          git config --global user.email "xianyongjian080402@126.com"
          git config --global user.name xianyongjian08040202
          git add .
          git commit -m "Update hosts"
        continue-on-error: true
      - name: Check on failures
        if: steps.commit.outputs.status == 'failure'
        run: exit 1
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOTTOKEN }}
  
